 <?php
/**
 * @global __
 * @global get_theme_mod
 * @global sanitize_hex_color
 * @global sanitize_checkbox
 * @global sanitize_text_field
 */

/**
 * Modern Business Customizer Settings: Sections with options from previous version merged
 *
 * @package Modern_Business
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$options = [
	'modern_business_sections_panel' => [
		'type'     => 'panel',
		'title'    => __( 'Sections', 'modern-business' ),
		'priority' => 30,
		'options'  => [
			// Hero Section
			'modern_business_hero_section' => [
				'type'     => 'section',
				'title'    => __( 'Hero Section', 'modern-business' ),
				'priority' => 10,
				'section'    => 'modern_business_sections_panel',
				'options'  => [
							'enable_hero_section' => [
								'type'              => 'checkbox',
								'control_type'      => 'checkbox',
								'label'             => __( 'Enable Hero Section', 'modern-business' ),
								'default'           => false,
								'sanitize_callback' => 'sanitize_checkbox',
								'priority'          => 1,
							],
							'hero_title' => [
								'type'              => 'text',
								'label'             => __( 'Hero Title', 'modern-business' ),
								'default'           => __( 'We Create Modern & Professional Websites', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 5,
							],
							'hero_subtitle' => [
								'type'              => 'textarea',
								'label'             => __( 'Hero Subtitle', 'modern-business' ),
								'default'           => __( 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis.', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 10,
							],
							'hero_background_color' => [
								'type'              => 'color',
								'control_type'      => 'color',
								'label'             => __( 'Background Color', 'modern-business' ),
								'default'           => '#ffffff',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 15,
								'active_callback'   => 'modern_business_is_hero_background_color_enabled',
							],
							'hero_background' => [
								'type'              => 'image',
								'control_type'      => 'image',
								'label'             => __( 'Hero Background Image', 'modern-business' ),
								'default'           => '',
								'sanitize_callback' => 'modern_business_sanitize_image',
								'priority'          => 45,
								'active_callback'   => 'modern_business_is_hero_background_color_enabled',
							],
							'hero_text_color' => [
								'type'              => 'color',
								'control_type'      => 'color',
								'label'             => __( 'Text Color', 'modern-business' ),
								'default'           => '#000000',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 20,
							],
							'hero_text_align' => [
								'type'              => 'select',
								'control_type'      => 'select',
								'label'             => __( 'Text Alignment', 'modern-business' ),
								'default'           => 'center',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 25,
								'choices'           => [
									'left'   => __( 'Left', 'modern-business' ),
									'center' => __( 'Center', 'modern-business' ),
									'right'  => __( 'Right', 'modern-business' ),
								],
							],
							'hero_padding_top' => [
								'type'              => 'text',
								'label'             => __( 'Padding Top', 'modern-business' ),
								'default'           => '50px',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 30,
							],
							'hero_padding_bottom' => [
								'type'              => 'text',
								'label'             => __( 'Padding Bottom', 'modern-business' ),
								'default'           => '50px',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 35,
							],
							'hero_font_size' => [
								'type'              => 'number',
								'label'             => __( 'Font Size (px)', 'modern-business' ),
								'default'           => 18,
								'sanitize_callback' => 'absint',
								'priority'          => 40,
								'input_attrs'       => [
									'min' => 10,
									'max' => 50,
								],
							],
							'hero_primary_btn_text' => [
								'type'              => 'text',
								'label'             => __( 'Primary Button Text', 'modern-business' ),
								'default'           => __( 'Get Started', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 50,
							],
							'hero_primary_btn_url' => [
								'type'              => 'url',
								'label'             => __( 'Primary Button URL', 'modern-business' ),
								'default'           => '#',
								'sanitize_callback' => 'esc_url_raw',
								'priority'          => 55,
							],
							'hero_secondary_btn_text' => [
								'type'              => 'text',
								'label'             => __( 'Secondary Button Text', 'modern-business' ),
								'default'           => __( 'Learn More', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 60,
							],
							'hero_secondary_btn_url' => [
								'type'              => 'url',
								'label'             => __( 'Secondary Button URL', 'modern-business' ),
								'default'           => '#',
								'sanitize_callback' => 'esc_url_raw',
								'priority'          => 65,
							],
						],
					],
					//Hero Slider Option
					'modern_business_hero_slider_section' => [
						'type'            => 'section',
						'title'           => __( 'Hero Slider Settings', 'modern-business' ),
						'priority'        => 20,
						'active_callback' => 'modern_business_is_hero_section_enabled',
						'options'         => [
							'enable_hero_slider' => [
								'type'              => 'checkbox',
								'control_type'      => 'checkbox',
								'label'             => __( 'Enable Hero Slider', 'modern-business' ),
								'default'           => false,
								'sanitize_callback' => 'sanitize_checkbox',
								'priority'          => 1,
							],
							'hero_slider_transition' => [
								'type'              => 'select',
								'control_type'      => 'select',
								'label'             => __( 'Transition Effect', 'modern-business' ),
								'default'           => 'fade',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 5,
								'choices'           => [
									'fade'  => __( 'Fade', 'modern-business' ),
									'slide' => __( 'Slide', 'modern-business' ),
									'zoom'  => __( 'Zoom', 'modern-business' ),
									'flip'  => __( 'Flip', 'modern-business' ),
								],
								'active_callback'   => 'modern_business_is_hero_slider_options_enabled',
							],
							'hero_slider_random_transitions' => [
								'type'              => 'checkbox',
								'control_type'      => 'checkbox',
								'label'             => __( 'Use Random Transitions', 'modern-business' ),
								'default'           => false,
								'sanitize_callback' => 'sanitize_checkbox',
								'priority'          => 10,
								'active_callback'   => 'modern_business_is_hero_slider_options_enabled',
							],
							'hero_slider_image_1' => [
								'type'              => 'image',
								'control_type'      => 'image',
								'label'             => __( 'Slider Image 1', 'modern-business' ),
								'default'           => '',
								'sanitize_callback' => 'modern_business_sanitize_image',
								'priority'          => 15,
								'active_callback'   => 'modern_business_is_hero_slider_options_enabled',
							],
							'hero_slider_image_2' => [
								'type'              => 'image',
								'control_type'      => 'image',
								'label'             => __( 'Slider Image 2', 'modern-business' ),
								'default'           => '',
								'sanitize_callback' => 'modern_business_sanitize_image',
								'priority'          => 20,
								'active_callback'   => 'modern_business_is_hero_slider_options_enabled',
							],
							'hero_slider_image_3' => [
								'type'              => 'image',
								'control_type'      => 'image',
								'label'             => __( 'Slider Image 3', 'modern-business' ),
								'default'           => '',
								'sanitize_callback' => 'modern_business_sanitize_image',
								'priority'          => 25,
								'active_callback'   => 'modern_business_is_hero_slider_options_enabled',
							],
							'hero_slider_image_4' => [
								'type'              => 'image',
								'control_type'      => 'image',
								'label'             => __( 'Slider Image 4', 'modern-business' ),
								'default'           => '',
								'sanitize_callback' => 'modern_business_sanitize_image',
								'priority'          => 30,
								'active_callback'   => 'modern_business_is_hero_slider_options_enabled',
							],
							'hero_slider_image_5' => [
								'type'              => 'image',
								'control_type'      => 'image',
								'label'             => __( 'Slider Image 5', 'modern-business' ),
								'default'           => '',
								'sanitize_callback' => 'modern_business_sanitize_image',
								'priority'          => 35,
								'active_callback'   => 'modern_business_is_hero_slider_options_enabled',
							],
							'hero_slider_overlay' => [
								'type'              => 'select',
								'control_type'      => 'select',
								'label'             => __( 'Slider Overlay', 'modern-business' ),
								'default'           => 'none',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 40,
								'choices'           => [
									'none'  => __( 'None', 'modern-business' ),
									'light' => __( 'Light', 'modern-business' ),
									'dark'  => __( 'Dark', 'modern-business' ),
								],
								'active_callback'   => 'modern_business_is_hero_slider_options_enabled',
							],
						],
					],
			// About Section
			'modern_business_about_section' => [
						'type'     => 'section',
						'title'    => __( 'About Section Options', 'modern-business' ),
						'priority' => 30,
						'options'  => [
							'enable_about_section' => [
								'type'              => 'checkbox',
								'control_type'      => 'checkbox',
								'label'             => __( 'Enable About Section', 'modern-business' ),
								'default'           => true,
								'sanitize_callback' => 'sanitize_checkbox',
								'priority'          => 1,
							],
							'about_title' => [
								'type'              => 'text',
								'label'             => __( 'About Title', 'modern-business' ),
								'default'           => __( 'About Us', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 5,
							],
							'about_subtitle' => [
								'type'              => 'textarea',
								'label'             => __( 'About Subtitle', 'modern-business' ),
								'default'           => __( 'Learn more about our company', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 10,
							],
							'about_bg_color' => [
								'type'              => 'color',
								'label'             => __( 'Background Color', 'modern-business' ),
								'default'           => '#ffffff',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 15,
							],
							'about_text_color' => [
								'type'              => 'color',
								'label'             => __( 'Text Color', 'modern-business' ),
								'default'           => '#000000',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 25,
							],
							'about_text_align' => [
								'type'              => 'select',
								'control_type'      => 'select',
								'label'             => __( 'Text Alignment', 'modern-business' ),
								'default'           => 'center',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 30,
								'choices'           => [
									'left'   => __( 'Left', 'modern-business' ),
									'center' => __( 'Center', 'modern-business' ),
									'right'  => __( 'Right', 'modern-business' ),
								],
							],
							'about_padding_top' => [
								'type'              => 'text',
								'label'             => __( 'Padding Top', 'modern-business' ),
								'default'           => '50px',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 35,
							],
							'about_padding_bottom' => [
								'type'              => 'text',
								'label'             => __( 'Padding Bottom', 'modern-business' ),
								'default'           => '50px',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 40,
							],
							'about_font_size' => [
								'type'              => 'number',
								'label'             => __( 'Font Size (px)', 'modern-business' ),
								'default'           => 18,
								'sanitize_callback' => 'absint',
								'priority'          => 45,
								'input_attrs'       => [
									'min' => 10,
									'max' => 50,
								],
							],
						],
					],
			// Services Section
					'modern_business_services_section_options' => [
						'type'     => 'section',
						'title'    => __( 'Services Section Options', 'modern-business' ),
						'priority' => 40,
						'panel'    => 'modern_business_services_section',
						'options'  => [
							'enable_services_section' => [
								'type'              => 'checkbox',
								'control_type'      => 'checkbox',
								'label'             => __( 'Enable Services Section', 'modern-business' ),
								'default'           => true,
								'sanitize_callback' => 'sanitize_checkbox',
								'priority'          => 1,
							],
							'services_title' => [
								'type'              => 'text',
								'label'             => __( 'Section Title', 'modern-business' ),
								'default'           => __( 'Our Services', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 2,
							],
							'services_subtitle' => [
								'type'              => 'textarea',
								'label'             => __( 'Section Subtitle', 'modern-business' ),
								'default'           => __( 'We offer a wide range of services to meet your needs', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 3,
							],
							'services_count' => [
								'type'              => 'number',
								'label'             => __( 'Number of Services', 'modern-business' ),
								'default'           => 6,
								'sanitize_callback' => 'absint',
								'priority'          => 4,
								'input_attrs'       => [
									'min' => 1,
									'max' => 20,
								],
							],
							'services_bg_color' => [
								'type'              => 'color',
								'label'             => __( 'Background Color', 'modern-business' ),
								'default'           => '#ffffff',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 5,
							],
							'services_text_color' => [
								'type'              => 'color',
								'label'             => __( 'Text Color', 'modern-business' ),
								'default'           => '#000000',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 10,
							],
							'services_padding_top' => [
								'type'              => 'text',
								'label'             => __( 'Padding Top', 'modern-business' ),
								'default'           => '50px',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 15,
							],
							'services_padding_bottom' => [
								'type'              => 'text',
								'label'             => __( 'Padding Bottom', 'modern-business' ),
								'default'           => '50px',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 20,
							],
							'services_font_size' => [
								'type'              => 'number',
								'label'             => __( 'Font Size (px)', 'modern-business' ),
								'default'           => 18,
								'sanitize_callback' => 'absint',
								'priority'          => 25,
								'input_attrs'       => [
									'min' => 10,
									'max' => 50,
								],
							],
						],
					],
			// Portfolio Section
					'modern_business_portfolio_section_options' => [
						'type'     => 'section',
						'title'    => __( 'Portfolio Section Options', 'modern-business' ),
						'priority' => 50,
						'options'  => [
							'enable_portfolio_section' => [
								'type'              => 'checkbox',
								'control_type'      => 'checkbox',
								'label'             => __( 'Enable Portfolio Section', 'modern-business' ),
								'default'           => true,
								'sanitize_callback' => 'sanitize_checkbox',
								'priority'          => 1,
							],
							'portfolio_title' => [
								'type'              => 'text',
								'label'             => __( 'Portfolio Title', 'modern-business' ),
								'default'           => __( 'Our Portfolio', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 5,
							],
							'portfolio_subtitle' => [
								'type'              => 'textarea',
								'label'             => __( 'Portfolio Subtitle', 'modern-business' ),
								'default'           => __( 'Check out our latest projects', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 10,
							],
							'portfolio_count' => [
								'type'              => 'number',
								'label'             => __( 'Number of Portfolio Items', 'modern-business' ),
								'default'           => 6,
								'sanitize_callback' => 'absint',
								'priority'          => 15,
								'input_attrs'       => [
									'min' => 1,
									'max' => 20,
								],
							],
							'portfolio_bg_color' => [
								'type'              => 'color',
								'label'             => __( 'Background Color', 'modern-business' ),
								'default'           => '#ffffff',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 20,
							],
							'portfolio_text_color' => [
								'type'              => 'color',
								'label'             => __( 'Text Color', 'modern-business' ),
								'default'           => '#000000',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 30,
							],
							'portfolio_text_align' => [
								'type'              => 'select',
								'control_type'      => 'select',
								'label'             => __( 'Text Alignment', 'modern-business' ),
								'default'           => 'center',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 35,
								'choices'           => [
									'left'   => __( 'Left', 'modern-business' ),
									'center' => __( 'Center', 'modern-business' ),
									'right'  => __( 'Right', 'modern-business' ),
								],
							],
							'portfolio_padding_top' => [
								'type'              => 'text',
								'label'             => __( 'Padding Top', 'modern-business' ),
								'default'           => '50px',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 40,
							],
							'portfolio_padding_bottom' => [
								'type'              => 'text',
								'label'             => __( 'Padding Bottom', 'modern-business' ),
								'default'           => '50px',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 45,
							],
							'portfolio_font_size' => [
								'type'              => 'number',
								'label'             => __( 'Font Size (px)', 'modern-business' ),
								'default'           => 18,
								'sanitize_callback' => 'absint',
								'priority'          => 50,
								'input_attrs'       => [
									'min' => 10,
									'max' => 50,
								],
							],
							'portfolio_primary_btn_text' => [
								'type'              => 'text',
								'label'             => __( 'Primary Button Text', 'modern-business' ),
								'default'           => __( 'View More', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 55,
							],
							'portfolio_primary_btn_url' => [
								'type'              => 'url',
								'label'             => __( 'Primary Button URL', 'modern-business' ),
								'default'           => '#',
								'sanitize_callback' => 'esc_url_raw',
								'priority'          => 60,
							],
						],
					],
			// Team Section
					'modern_business_team_section_options' => [
						'type'     => 'section',
						'title'    => __( 'Team Section Options', 'modern-business' ),
						'priority' => 60,
						'panel'    => 'modern_business_team_section',
						'options'  => [
							'enable_team_section' => [
								'type'              => 'checkbox',
								'control_type'      => 'checkbox',
								'label'             => __( 'Enable Team Section', 'modern-business' ),
								'default'           => true,
								'sanitize_callback' => 'sanitize_checkbox',
								'priority'          => 1,
							],
							'team_title' => [
								'type'              => 'text',
								'label'             => __( 'Section Title', 'modern-business' ),
								'default'           => __( 'Our Team', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 2,
							],
							'team_subtitle' => [
								'type'              => 'textarea',
								'label'             => __( 'Section Subtitle', 'modern-business' ),
								'default'           => __( 'Meet the people behind our success', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 3,
							],
							'team_count' => [
								'type'              => 'number',
								'label'             => __( 'Number of Team Members', 'modern-business' ),
								'default'           => 4,
								'sanitize_callback' => 'absint',
								'priority'          => 4,
								'input_attrs'       => [
									'min' => 1,
									'max' => 20,
								],
							],
							'team_bg_color' => [
								'type'              => 'color',
								'label'             => __( 'Background Color', 'modern-business' ),
								'default'           => '#ffffff',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 5,
							],
							'team_text_color' => [
								'type'              => 'color',
								'label'             => __( 'Text Color', 'modern-business' ),
								'default'           => '#000000',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 10,
							],
							'team_padding_top' => [
								'type'              => 'text',
								'label'             => __( 'Padding Top', 'modern-business' ),
								'default'           => '50px',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 15,
							],
							'team_padding_bottom' => [
								'type'              => 'text',
								'label'             => __( 'Padding Bottom', 'modern-business' ),
								'default'           => '50px',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 20,
							],
							'team_font_size' => [
								'type'              => 'number',
								'label'             => __( 'Font Size (px)', 'modern-business' ),
								'default'           => 18,
								'sanitize_callback' => 'absint',
								'priority'          => 25,
								'input_attrs'       => [
									'min' => 10,
									'max' => 50,
								],
							],
						],
					],
			// Testimonials Section
					'modern_business_testimonials_section_options' => [
						'type'     => 'section',
						'title'    => __( 'Testimonials Section Options', 'modern-business' ),
						'priority' => 70,
						'options'  => [
							'enable_testimonials_section' => [
								'type'              => 'checkbox',
								'control_type'      => 'checkbox',
								'label'             => __( 'Enable Testimonials Section', 'modern-business' ),
								'default'           => true,
								'sanitize_callback' => 'sanitize_checkbox',
								'priority'          => 1,
							],
							'testimonials_title' => [
								'type'              => 'text',
								'label'             => __( 'Testimonials Title', 'modern-business' ),
								'default'           => __( 'Testimonials', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 5,
							],
							'testimonials_subtitle' => [
								'type'              => 'textarea',
								'label'             => __( 'Testimonials Subtitle', 'modern-business' ),
								'default'           => __( 'What our clients say about us', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 10,
							],
							'testimonials_bg_color' => [
								'type'              => 'color',
								'label'             => __( 'Background Color', 'modern-business' ),
								'default'           => '#ffffff',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 15,
							],
							'testimonials_text_color' => [
								'type'              => 'color',
								'label'             => __( 'Text Color', 'modern-business' ),
								'default'           => '#000000',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 25,
							],
							'testimonials_text_align' => [
								'type'              => 'select',
								'control_type'      => 'select',
								'label'             => __( 'Text Alignment', 'modern-business' ),
								'default'           => 'center',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 30,
								'choices'           => [
									'left'   => __( 'Left', 'modern-business' ),
									'center' => __( 'Center', 'modern-business' ),
									'right'  => __( 'Right', 'modern-business' ),
								],
							],
							'testimonials_padding_top' => [
								'type'              => 'text',
								'label'             => __( 'Padding Top', 'modern-business' ),
								'default'           => '50px',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 35,
							],
							'testimonials_padding_bottom' => [
								'type'              => 'text',
								'label'             => __( 'Padding Bottom', 'modern-business' ),
								'default'           => '50px',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 40,
							],
							'testimonials_font_size' => [
								'type'              => 'number',
								'label'             => __( 'Font Size (px)', 'modern-business' ),
								'default'           => 18,
								'sanitize_callback' => 'absint',
								'priority'          => 45,
								'input_attrs'       => [
									'min' => 10,
									'max' => 50,
								],
							],
						],
					],
			// Blog Section
					'modern_business_blog_section_options' => [
						'type'     => 'section',
						'title'    => __( 'Blog Section Options', 'modern-business' ),
						'priority' => 80,
						'panel'    => 'modern_business_blog_section',
						'options'  => [
							'enable_blog_section' => [
								'type'              => 'checkbox',
								'control_type'      => 'checkbox',
								'label'             => __( 'Enable Blog Section', 'modern-business' ),
								'default'           => true,
								'sanitize_callback' => 'sanitize_checkbox',
								'priority'          => 1,
							],
							'blog_bg_color' => [
								'type'              => 'color',
								'label'             => __( 'Background Color', 'modern-business' ),
								'default'           => '#ffffff',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 5,
							],
							'blog_text_color' => [
								'type'              => 'color',
								'label'             => __( 'Text Color', 'modern-business' ),
								'default'           => '#000000',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 10,
							],
							'blog_padding_top' => [
								'type'              => 'text',
								'label'             => __( 'Padding Top', 'modern-business' ),
								'default'           => '50px',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 15,
							],
							'blog_padding_bottom' => [
								'type'              => 'text',
								'label'             => __( 'Padding Bottom', 'modern-business' ),
								'default'           => '50px',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 20,
							],
							'blog_font_size' => [
								'type'              => 'number',
								'label'             => __( 'Font Size (px)', 'modern-business' ),
								'default'           => 18,
								'sanitize_callback' => 'absint',
								'priority'          => 25,
								'input_attrs'       => [
									'min' => 10,
									'max' => 50,
								],
							],
						],
					],
			// Contact Section
					'modern_business_contact_section_options' => [
						'type'     => 'section',
						'title'    => __( 'Contact Section Options', 'modern-business' ),
						'priority' => 90,
						'options'  => [
							'enable_contact_section' => [
								'type'              => 'checkbox',
								'control_type'      => 'checkbox',
								'label'             => __( 'Enable Contact Section', 'modern-business' ),
								'default'           => true,
								'sanitize_callback' => 'sanitize_checkbox',
								'priority'          => 1,
							],
							'contact_title' => [
								'type'              => 'text',
								'label'             => __( 'Contact Title', 'modern-business' ),
								'default'           => __( 'Contact Us', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 2,
							],
							'contact_subtitle' => [
								'type'              => 'textarea',
								'label'             => __( 'Contact Subtitle', 'modern-business' ),
								'default'           => __( 'Get in touch with us', 'modern-business' ),
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 3,
							],
							'contact_phone' => [
								'type'              => 'text',
								'label'             => __( 'Phone Number', 'modern-business' ),
								'default'           => '(123) 456-7890',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 4,
								],
								'contact_email' => [
								'type'              => 'text',
								'label'             => __( 'Email Address', 'modern-business' ),
								'default'           => 'info@example.com',
								'sanitize_callback' => 'sanitize_email',
								'priority'          => 5,
								],
								'contact_address' => [
								'type'              => 'textarea',
								'label'             => __( 'Physical Address', 'modern-business' ),
								'default'           => '123 Main St, City, Country',
								'sanitize_callback' => 'sanitize_textarea_field',
								'priority'          => 6,
								],
															'contact_form_shortcode' => [
								'type'              => 'text',
								'label'             => __( 'Contact Form Shortcode', 'modern-business' ),
								'default'           => '',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 7,
								],

							'contact_bg_color' => [
								'type'              => 'color',
								'label'             => __( 'Background Color', 'modern-business' ),
								'default'           => '#ffffff',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 8,
							],
							'contact_info_bg_color' => [
								'type'              => 'color',
								'control_type'      => 'color',
								'label'             => __( 'Contact Info Background Color', 'modern-business' ),
								'default'           => '#f5f5f5',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 9,
							],
							'contact_text_color' => [
								'type'              => 'color',
								'label'             => __( 'Text Color', 'modern-business' ),
								'default'           => '#000000',
								'sanitize_callback' => 'sanitize_hex_color',
								'priority'          => 10,
							],
							'contact_text_align' => [
								'type'              => 'select',
								'control_type'      => 'select',
								'label'             => __( 'Text Alignment', 'modern-business' ),
								'default'           => 'center',
								'sanitize_callback' => 'sanitize_text_field',
								'priority'          => 11,
								'choices'           => [
									'left'   => __( 'Left', 'modern-business' ),
									'center' => __( 'Center', 'modern-business' ),
									'right'  => __( 'Right', 'modern-business' ),
								],
					],
				],
			],
			'modern_business_general_settings_panel' => [
				'type'     => 'panel',
				'title'    => __( 'General Settings', 'modern-business' ),
				'priority' => 20,
				'options'  => [
					'general_colors_section' => [
							'type'     => 'section',
							'title'    => __( 'Colors', 'modern-business' ),
							'priority' => 10,
							'options'  => [
								'general_text_color' => [
									'type'              => 'color',
									'control_type'      => 'color',
									'label'             => __( 'General Text Color', 'modern-business' ),
									'default'           => '#000000',
									'sanitize_callback' => 'sanitize_hex_color',
									'priority'          => 1,
								],
								'general_background_color' => [
									'type'              => 'color',
									'control_type'      => 'color',
									'label'             => __( 'General Background Color', 'modern-business' ),
									'default'           => '#ffffff',
									'sanitize_callback' => 'sanitize_hex_color',
									'priority'          => 2,
								],
							],
					],
					'general_typography_section' => [
							'type'     => 'section',
							'title'    => __( 'Typography', 'modern-business' ),
							'priority' => 20,
							'options'  => [
'general_font_family' => [
	'type'              => 'select',
	'control_type'      => 'select',
	'label'             => __( 'General Font Family', 'modern-business' ),
	'default'           => 'Arial, sans-serif',
	'sanitize_callback' => 'sanitize_text_field',
	'priority'          => 1,
	'choices'           => [
		'Arial, sans-serif'           => 'Arial',
		'Helvetica, sans-serif'       => 'Helvetica',
		'"Times New Roman", serif'    => 'Times New Roman',
		'Georgia, serif'              => 'Georgia',
		'Verdana, sans-serif'         => 'Verdana',
		'"Courier New", monospace'    => 'Courier New',
		'"Lucida Console", monospace' => 'Lucida Console',
		'Roboto, sans-serif'          => 'Roboto',
		'Open Sans, sans-serif'       => 'Open Sans',
		'Lato, sans-serif'            => 'Lato',
		'Montserrat, sans-serif'      => 'Montserrat',
		'Oswald, sans-serif'          => 'Oswald',
		'Source Sans Pro, sans-serif' => 'Source Sans Pro',
		'Raleway, sans-serif'         => 'Raleway',
		'Merriweather, serif'         => 'Merriweather',
	],
],
								'general_font_size' => [
									'type'              => 'number',
									'label'             => __( 'General Font Size (px)', 'modern-business' ),
									'default'           => 16,
									'sanitize_callback' => 'absint',
									'priority'          => 2,
									'input_attrs'       => [
											'min' => 10,
											'max' => 50,
									],
								],
							],
        ],
    ],
],

		],
	],
];

return $options;
